apiVersion: v1
kind: Pod
metadata:
  name: influx-stress-js
spec:
  restartPolicy: Never
  containers:
    - image: index.caicloud.io/caicloud/influxdb-stress
      imagePullPolicy: IfNotPresent
      name: influxdb
      env:
      - name: RATE
        value: "100"
      - name: RUNTIME
        value: "10"
      - name: DB
        value: mydb
      - name: HOSTNAME
        value: monitoring-influxdb
      - name: PORT
        value: "8086"
